import type { ContractorVisit } from "./types"

export const demoData: ContractorVisit[] = [
  {
    id: "1",
    contractorName: "John Smith",
    company: "ABC Electrical Services",
    jobType: "Electrical Maintenance",
    description: "Quarterly electrical system inspection and maintenance",
    date: "2025-03-15",
    timeIn: "09:00",
    timeOut: "12:30",
    status: "Completed",
    recurrence: "Quarterly",
    nextScheduled: "2025-06-15",
    contactEmail: "john@abcelectrical.com",
    contactPhone: "(555) 123-4567",
  },
  {
    id: "2",
    contractorName: "Sarah Johnson",
    company: "CleanPro Services",
    jobType: "Cleaning",
    description: "Weekly office deep cleaning",
    date: "2025-03-18",
    timeIn: "18:00",
    timeOut: "22:00",
    status: "Completed",
    recurrence: "Weekly",
    nextScheduled: "2025-03-25",
    contactEmail: "sarah@cleanpro.com",
    contactPhone: "(555) 234-5678",
  },
  {
    id: "3",
    contractorName: "Mike Chen",
    company: "HVAC Solutions Inc",
    jobType: "HVAC Service",
    description: "Monthly HVAC system check and filter replacement",
    date: "2025-03-20",
    timeIn: "10:00",
    timeOut: "14:00",
    status: "Completed",
    recurrence: "Monthly",
    nextScheduled: "2025-04-20",
    contactEmail: "mike@hvacsolutions.com",
    contactPhone: "(555) 345-6789",
  },
  {
    id: "4",
    contractorName: "Emily Rodriguez",
    company: "GreenScape Landscaping",
    jobType: "Landscaping",
    description: "Weekly lawn maintenance and garden care",
    date: "2025-03-22",
    timeIn: "08:00",
    timeOut: "11:00",
    status: "In Progress",
    recurrence: "Weekly",
    nextScheduled: "2025-03-29",
    contactEmail: "emily@greenscape.com",
    contactPhone: "(555) 456-7890",
  },
  {
    id: "5",
    contractorName: "David Park",
    company: "SecureIT Systems",
    jobType: "IT Security",
    description: "Security system audit and updates",
    date: "2025-03-25",
    timeIn: "09:00",
    timeOut: "17:00",
    status: "Scheduled",
    recurrence: "Quarterly",
    nextScheduled: "2025-06-25",
    contactEmail: "david@secureit.com",
    contactPhone: "(555) 567-8901",
  },
  {
    id: "6",
    contractorName: "Lisa Thompson",
    company: "PlumbPro",
    jobType: "Plumbing",
    description: "Emergency pipe repair in basement",
    date: "2025-03-10",
    timeIn: "14:00",
    timeOut: "16:30",
    status: "Completed",
    recurrence: "One-time",
    contactEmail: "lisa@plumbpro.com",
    contactPhone: "(555) 678-9012",
  },
  {
    id: "7",
    contractorName: "Robert Williams",
    company: "FireSafe Inspections",
    jobType: "Fire Safety",
    description: "Annual fire safety inspection and equipment testing",
    date: "2025-03-28",
    timeIn: "10:00",
    timeOut: "15:00",
    status: "Scheduled",
    recurrence: "Quarterly",
    nextScheduled: "2025-06-28",
    contactEmail: "robert@firesafe.com",
    contactPhone: "(555) 789-0123",
  },
  {
    id: "8",
    contractorName: "Amanda Lee",
    company: "PestControl Plus",
    jobType: "Pest Control",
    description: "Monthly pest inspection and treatment",
    date: "2025-03-12",
    timeIn: "11:00",
    timeOut: "13:00",
    status: "Completed",
    recurrence: "Monthly",
    nextScheduled: "2025-04-12",
    contactEmail: "amanda@pestcontrolplus.com",
    contactPhone: "(555) 890-1234",
  },
  {
    id: "9",
    contractorName: "James Martinez",
    company: "Window Wizards",
    jobType: "Window Cleaning",
    description: "Bi-weekly exterior window cleaning",
    date: "2025-03-14",
    timeIn: "08:00",
    timeOut: "12:00",
    status: "Completed",
    recurrence: "Weekly",
    nextScheduled: "2025-03-28",
    contactEmail: "james@windowwizards.com",
    contactPhone: "(555) 901-2345",
  },
  {
    id: "10",
    contractorName: "Patricia Brown",
    company: "Elevator Tech Services",
    jobType: "Elevator Maintenance",
    description: "Monthly elevator inspection and maintenance",
    date: "2025-03-30",
    timeIn: "07:00",
    timeOut: "10:00",
    status: "Scheduled",
    recurrence: "Monthly",
    nextScheduled: "2025-04-30",
    contactEmail: "patricia@elevatortech.com",
    contactPhone: "(555) 012-3456",
  },
]
